name: Build LaTeX book
on: [push]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: xu-cheng/texlive-action@v2
        with:
          scheme: full
          run: |
            apk add py3-pygments

      - name: List Files
        run: ls

      - name: List Output Files
        run: ls /home/runner/work/atlas/atlas/competitive.pdf

      - name: Upload PDF file
        uses: actions/upload-artifact@v4
        with:
          name: PDF
          path: /home/runner/work/atlas/atlas/competitive.pdf
